// The "database": normalized tables loaded in memory and indexed by id.
// Each table is an object { all, byId, get }. The JSON is generated by scripts/migrate.mjs.
//
// Why separate tables instead of inlining everything: docs/schema.html. Short version:
// one item (けす) appears in many exercises and one exercise (MC) uses many items
// → many-to-many, which can't live in a single table without duplicating.
import itemsJson from '../data/items.json';
import exercisesJson from '../data/exercises.json';
import lessonsJson from '../data/lessons.json';
import type { Item, Exercise, Lesson, Skill } from './types';

interface Table<T extends { id: string }> {
  all: T[];
  byId: Map<string, T>;
  get(id: string): T | undefined;
}

function table<T extends { id: string }>(rows: T[]): Table<T> {
  const byId = new Map(rows.map((r) => [r.id, r]));
  return { all: rows, byId, get: (id) => byId.get(id) };
}

export const db = {
  items: table(itemsJson as Item[]),
  exercises: table(exercisesJson as Exercise[]),
  lessons: table(lessonsJson as Lesson[]),
};

/* ---------- queries ("JOIN" is a lookup by id) ---------- */

/** The lexicon item an exercise references (conjugate / vocab), if any. */
export const itemOf = (ex: Exercise): Item | undefined =>
  ex.itemId ? db.items.get(ex.itemId) : undefined;

/** A lesson's exercises, in order. */
export const exercisesOf = (lesson: Lesson): Exercise[] =>
  lesson.exerciseIds.map((id) => db.exercises.get(id)).filter((e): e is Exercise => !!e);

export const exercisesBySkill = (skill: Skill): Exercise[] =>
  db.exercises.all.filter((e) => e.skill === skill);

export const lessonsInOrder = (): Lesson[] =>
  [...db.lessons.all].sort((a, b) => a.position - b.position);

/** Distractors for a vocab MC: meanings of other items (avoids duplicating data). */
export const meaningDistractors = (correctId: string, n = 3): string[] => {
  const pool = db.items.all.filter((i) => i.id !== correctId).map((i) => i.meaning);
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, n);
};
