export type Group = 1 | 2 | 3;

export type FormKey =
  | 'dict' | 'masu' | 'nai' | 'ta' | 'nakatta' | 'te' | 'tari' | 'nakereba';

export type Forms = Record<FormKey, string>;

/* ---------- Normalized model (tables) — see docs/schema.html ----------
 * Generated by scripts/migrate.mjs; consumed by lib/db.ts. */

/** A lexicon word. Verb attributes (group, falseG2) only when kind='verb'.
 *  Furigana: `furi` reads ONLY over the kanji; `okuri` stays as loose kana —
 *  so you can see whether the い/え vowel sits inside the kanji (usually Group 1)
 *  or in the okurigana (Group 2). */
export type ItemKind = 'verb' | 'noun' | 'adj_i' | 'adj_na' | 'phrase';
export interface Item {
  id: string;
  kind: ItemKind;
  kanji?: string;
  furi?: string;
  okuri?: string;
  kana: string;
  meaning: string;
  group?: Group;      // verbs only
  falseG2?: boolean;  // verbs only
}

/** One question row. `skill` = pedagogical axis; `type` = how it's rendered and graded. */
export type Skill = 'grammar' | 'vocab' | 'conjugation';
export type ExerciseType = 'mc' | 'type' | 'conjugate';
export interface Exercise {
  id: string;
  skill: Skill;
  type: ExerciseType;
  chapter?: number;
  topic?: string;
  prompt?: string;
  cue?: string;
  exp?: string;
  options?: string[];    // type=mc
  correct?: number;      // type=mc
  answers?: string[];    // type=type
  itemId?: string;       // → Item.id (conjugate / vocab)
  params?: Record<string, unknown>; // conjugate config (what to ask / mode)
}

/** Ordered group of exercises — the Duolingo-style path. */
export interface Lesson {
  id: string;
  title: string;
  subtitle?: string;
  position: number;
  chapter?: number;
  exerciseIds: string[];
}
